
import type { Car, Testimonial } from './types';

export const TESTIMONIALS: Testimonial[] = [
  {
    author: 'Sarah M.',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA_AL6JamhPqsYN_kA44Ol0g1WlyfPxORD1seLqO3z-S6MFOjTlMA5iiHPVvEtQyvZkYTDUPezRVWMMUM4vvKdl_IIxLaLRgs1-QHdoR3YiidS0JeKilKWEMxw10dvJMwOSQjS55nP4jM2uYPJLMsu1V0k5mDuAvYYd0lBglRyY13bNxoXZGH9ibAmrObzo0L3p6CI-6VrSTIjr4wsM416XCayBrK2G3OhuE4JIL_L6_0fUJgrCeHkalVe-66-RAQdQ5A1I7aFcW7k',
    comment: 'The car was immaculate and the service was top-notch. Will definitely use DriveShare again!',
    rating: 5,
  },
  {
    author: 'David L.',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC457by5Agh37-KxRNe6MmlHZoxTYnYL8uUkvOLCDnio-3qYWxtLNEdn1ipx8OvS7hTnUVrLfdjF3mGIevqNb1klzlO8GZq0-f_eGt_ZMaw9H5y8h4JzwjbC8D7sg8xkZTcqekVWNoizDkwVAdQaOX1v9S8y47yzR7ExU6clmZ6Nxv0VKekbp6tf5K2ncxIwdJvdOGVyPjMMruR6tJzcftYzO4FmU0Nsf8dWxEN-MvSLaHnmpVOd51NOPM3jTHodxg0plpWs5-nJeY',
    comment: 'DriveShare made renting a luxury car a breeze. Highly recommend!',
    rating: 5,
  },
  {
    author: 'Emily R.',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMcHYrPYl87ClimE-zrRrvkSL8t2K7wYkBDL_YgYImn4lF0wMTD5j9pwNsQIdwPFEdV2B2on6AhlRfuDBBp_3nKi-4WJX8sMCcbvl3n0mAXv3eFnpvCqj3P_gLJgYyU6sI6YLKx_aUrcDQj-TJOWe6qWVY_Djgq8HTGhIXRwadMewd6qksmCnW8XHMQVTpx4PJ58elfKJWjZ9342o8sCiUlI1r7RGe_yA7PIrvI1TgS3fBGxwDuhSOeXr_Fr-M_oQFKraIotkaMAQ',
    comment: 'Fantastic experience from start to finish. The car was perfect for our weekend getaway.',
    rating: 4.5,
  },
];


export const CARS: Car[] = [
  {
    id: 1,
    name: 'Tesla Model S',
    description: 'Sleek, fast, and fully electric.',
    pricePerDay: 150,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEhS-zHskmBWFH56a6OXJetKjXmZVSAjIoASXHcuz7d6_gHVYIs3gv6GkQFsZXmr4tcdIckFOEMYbgaQpM8P_DApgyDn6bFEC-79E2Ese2z9N2byEhg6Q3VZVjtZax10bSTNWsGlqfNl94CBFEZ60vY0u6jOfFRlYPjXW9YCE7WJl_WxxZ5GeN647whPk2o2CErKNd8Y3VXVbRcjQQAw-dSPYPktAccgTek270vD3IqztgZwFn8wOM-0MzIRbecdcjn1NjWQqBWbY',
    gallery: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCzWOD_ADxEBS-E9yw0YtqOG_92I2VbXC5LxT1OVG5bMxTc7YDgIvZ0sSYexJ5KL-Ir5ZwRTbO1scOsmSTlhRvBeFTnyWSbM90ZW2RFP8cjJJNFqRfzecyhlgq4Cazmg1xa8pbEjbZ2VtC3d5vza0BQycgMpg3VSjq4nq516X6MESkdGkt6QvriVcaYlWgqPapQXlB4qEVdlw4UQOijl5o_MMMzKu3MVtwTFqTYmp9tzohrQvv62WCIvkPliCYHK1ts_KOiKi3OwEw',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA5ZrA9WyFLTICI8TUlv1TwjSf-knhoJ08wPjK9nNBdCGDiO1nBT93eo0tqzbzulNNBFHdbSGAOCRoqAwq5EhcJymbOBzPz96t1IaQ4vEGRoerL5TSK-5NrDX4XTMIcwKnJMAELHrkzrSLH7O0qFP-MOd2UMaZJ6sFQNfpePg4Wj8CRL_KzhXt6yHVXmtIe6ezQOyk-M6zC6PqicZ82WC2LVjJK5vSslyHmoWBWjECAMiyX1-mF4dJiSWznThEqoVis9U5Hw4MH5qM',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBy2-1LPZ-JW3bF9ECKbVIzft7xdx74abVAJSPmPsgw8Is0q32IgjGw9SvInG9vxtzCkexL8PLa7h0Gq93M_ldhI_kI5mG_oH2FGSnxh3mEFSHSg7Q3kv46OUopDfbtxbyjSZsksEd8WBmBEX1sAz-AjRass1JAIYT4XPXu2A9GKVji2DVgUAeaK9V9JgEHj66bc5eOyf3gkdXtzjcVWY0MtoyBK6SKUkBE4CBCgIJsyY1HFXHcYrqa4wciy8BYc7qFtxS5YzduoQw',
    ],
    specs: {
      year: 2023, seats: 5, transmission: 'Automatic', fuel: 'Electric', type: 'Sedan', ac: true,
    },
    features: ['Navigation', 'Bluetooth', 'Premium Sound', 'Autopilot', 'GPS'],
    location: '123 Market Street, San Francisco, CA',
    rating: 4.9,
    reviews: [
      {
        author: 'Ethan Carter',
        avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5QwTUbpNL2hDGWavX-CPVwQdgTozVV3qS_1EIbjO4-Wb7gHdwexV3hLRi0IHvDa9_jgZqX3I1f5xrNIUm6UlCqywKzP-FECmqwr_clWAq14LR5vflbxoFCMO_ynQWBms9rBU5C-02txKDO-Mly2XViIT3GSkVRxWlQUmwv0ttDBQvtxWf_q0bP8XGmQvXj4d25EH8Uq9aMM17VhJRE-jbmhydb4UixxQgJuD9Bvrap8fIjX5pDi3ngweqmpEUEystOKTP0gz_Yfg',
        date: 'Jul 1, 2024',
        comment: 'The car was immaculate and drove like a dream. The host was incredibly responsive and made the whole process seamless.',
        rating: 5,
      },
      {
        author: 'Olivia Bennett',
        avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8axjQ7f_QSs-orZQzq3rbVR8kIzkSFgyJPC9d8S0ekfCKxxb5DAXSMDgqM9FLSQaCcXbdfB2r77QTuUGtectu04MDqaPtxSCKaT6oSLWrXz2GPbXnQUKV8M2-MaGE3ZmyCK4LYEbTvfaAKlSn_sSpT8KJfNeMcKSI22v1f-Mkhvy0yyWH12Sc_aAK7IKlKCe9wccrOhaETGaFFi0G4qGp_xYr6hVFiZSbzALPbFxYF17zSbjtUOjT26RCU--L9A2EaHNh89FbSU8',
        date: 'Jun 20, 2024',
        comment: 'Fantastic experience! The car was perfect for our weekend getaway, and the host provided excellent service.',
        rating: 5,
      },
    ],
  },
  {
    id: 2,
    name: 'BMW 7 Series',
    description: 'Experience pure luxury and performance.',
    pricePerDay: 180,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGNp_WMrlhqxXpsuQclUgNg73qnhwSx8ncWEEVlBMHRVB1uKamP3qvu8qD_Tr9vh9L9vPa9Lx7qReycifx8FT0psdOgQoxd2xX3RIJQEmBoWlb4RdX2BmifTSdbOrmOt_EqnjBLrahg6TsqmhGs3WoJp5eagGANuR5RW5AefWiqqzmGSHjYnk6CFfSEtYotG0pkXdo4X8hVZISbMf4EUPRpVX8gNBo-pztZaR_Kpv1OReSP1_lJQ5kZz10AgzoaZZ-mDp3jh9Nm-4',
    gallery: ['https://picsum.photos/800/600?random=21', 'https://picsum.photos/800/600?random=22', 'https://picsum.photos/800/600?random=23'],
    specs: { year: 2022, seats: 5, transmission: 'Automatic', fuel: 'Gasoline', type: 'Sedan', ac: true },
    features: ['GPS', 'Bluetooth', 'Sunroof', 'Leather Seats'],
    location: '456 Grand Ave, Los Angeles, CA',
    rating: 4.8,
    reviews: [],
  },
  {
    id: 3,
    name: 'Mercedes-Benz S-Class',
    description: 'The pinnacle of automotive luxury.',
    pricePerDay: 200,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBs69f5xe_c2G9gmFiWK34LYiBgkqne5CJnAS2vxzRGmG9J_ORbMwxe4PC0Xjo2EhUCAHTQG9_qHNY-pc7fMx7--9oWn3H72d7utF9LAFHiG8kyxeu5NfpSPRhHSHfqqSNNNLgAsq3DuHUCPnLuFQ7pzinkAsyvUeCkKJefzWE_N0KjP63KgBXSyFozUpE7eGkxwhkcWIQcTIZpN94eudhaa5fBff2McJ9ajQjWEq0v3cvsTNSZvptDZgoBbd89AdcJ6Ar7_KwwLFU',
    gallery: ['https://picsum.photos/800/600?random=31', 'https://picsum.photos/800/600?random=32', 'https://picsum.photos/800/600?random=33'],
    specs: { year: 2023, seats: 5, transmission: 'Automatic', fuel: 'Hybrid', type: 'Sedan', ac: true },
    features: ['GPS', 'Bluetooth', 'Massaging Seats', 'Ambient Lighting'],
    location: '789 Ocean Drive, Miami, FL',
    rating: 4.9,
    reviews: [],
  },
  {
    id: 4,
    name: 'Ford Focus',
    description: 'A reliable and efficient hatchback.',
    pricePerDay: 51,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASUlB2IjAZRWHiO0E3Yq_UoWgdhWrYAf63Tr8NLP-vrKdrjcl2-4x6XC3pmb2R4RrMj8I0wpyCEWop9BAA3esPrZx2P7My3wQdcgAQJdU_P3kP5omqNmI6CqRQ5GcqVNM-jp_voz-TZC4Wwc2csHpjINT1UhS7VsBP0jISKxV7ZTP2JMXa3bXqF1v_3PKPo6iyND3N0WNfZ-IwuQ8jEom42Ho6BeXtorGkneY4rJtCxUA_IXA_3PVq-tDFuMnDRrEkn9ewci-dXiA',
    gallery: ['https://picsum.photos/800/600?random=41', 'https://picsum.photos/800/600?random=42'],
    specs: { year: 2021, seats: 5, transmission: 'Automatic', fuel: 'Gasoline', type: 'Hatchback', ac: true },
    features: ['Bluetooth', 'Child Seat'],
    location: '101 Main Street, Chicago, IL',
    rating: 4.5,
    reviews: [],
  },
  {
    id: 5,
    name: 'Ford Fiesta',
    description: 'Compact, fun to drive, and economical.',
    pricePerDay: 55,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRngsyBUzniqxhxzEyu0mUqOEyPOWfCcQ5xo-BKzWYM8ruW13-E8OobGpOYHFHIFX65MPlLGMOlsm9vMgv_-PWORrbzMYGHiB9Y8ygf35fer_09c6Hlpm4fiTJxiiNDtGzb2vMjPElilx8mlOSOXLluPKq4H12GIE6HXQzjFetAv4REOfj0L64EfpBmfWY0aQtLqqCHPqp8hxyeGWrbC4xWWnEv3dSupSN2WvTXnzwIIhHfTstoCxPzX0avAjtoq5pIJcELcfLSwI',
    gallery: ['https://picsum.photos/800/600?random=51', 'https://picsum.photos/800/600?random=52'],
    specs: { year: 2022, seats: 5, transmission: 'Automatic', fuel: 'Gasoline', type: 'Hatchback', ac: true },
    features: ['Bluetooth'],
    location: '212 Oak Street, Austin, TX',
    rating: 4.6,
    reviews: [],
  },
  {
    id: 6,
    name: 'Honda CRV',
    description: 'A versatile and spacious SUV for any adventure.',
    pricePerDay: 65,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKsMpj2FoyrFKUUh2WE-9s-JvGSenzSNjUtBEpdrermXW5DQA_2L9Z9Z6TvTQIW2N1Nbmti_Jdio8IUvBAR6XN_1e_FlO7ktwMoW0xMXT6OIlfVWPcuEyu7J3W7Eznxe-x2foGhLmIIgcNGJx2pbnHUutwg7flBg4puZxhtcjw0cWOtXpw7QBiw6-YDmW9Ua9o3hfS1-aTQVDDc1gMaxWuvcc7SOFT-sXU0ISmoAVhk08OijaszScGC_xCbEKmC_rfbd5FKajXjJg',
    gallery: ['https://picsum.photos/800/600?random=61', 'https://picsum.photos/800/600?random=62'],
    specs: { year: 2023, seats: 5, transmission: 'Automatic', fuel: 'Hybrid', type: 'SUV', ac: true },
    features: ['GPS', 'Bluetooth', 'Child Seat'],
    location: '333 Pine Blvd, Denver, CO',
    rating: 4.7,
    reviews: [],
  },
];
